"""fix delect user

Revision ID: 042ae9c1b14e
Revises: f8b21ac379df
Create Date: 2025-08-01 08:38:44.457247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042ae9c1b14e'
down_revision = 'f8b21ac379df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('daily_metrics_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('health_profiles_staff_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('health_profiles_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['staff_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('questionnaire_cat', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('questionnaire_cat_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('questionnaire_mmrc', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('questionnaire_mmrc_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('staff_details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('staff_details_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('staff_details_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('questionnaire_mmrc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('questionnaire_mmrc_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('questionnaire_cat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('questionnaire_cat_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('health_profiles_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('health_profiles_staff_id_fkey'), 'users', ['staff_id'], ['id'])

    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('daily_metrics_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
