"""empty message

Revision ID: f8b21ac379df
Revises: 6659197c8f75
Create Date: 2025-07-25 09:17:05.511212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b21ac379df'
down_revision = '6659197c8f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('water_cc', sa.Integer(), nullable=True),
    sa.Column('medication', sa.Boolean(), nullable=True),
    sa.Column('exercise_min', sa.Integer(), nullable=True),
    sa.Column('cigarettes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('smoke_status', sa.String(length=10), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('questionnaire_cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cough_score', sa.SmallInteger(), nullable=False),
    sa.Column('phlegm_score', sa.SmallInteger(), nullable=False),
    sa.Column('chest_score', sa.SmallInteger(), nullable=False),
    sa.Column('breath_score', sa.SmallInteger(), nullable=False),
    sa.Column('limit_score', sa.SmallInteger(), nullable=False),
    sa.Column('confidence_score', sa.SmallInteger(), nullable=False),
    sa.Column('sleep_score', sa.SmallInteger(), nullable=False),
    sa.Column('energy_score', sa.SmallInteger(), nullable=False),
    sa.Column('total_score', sa.SmallInteger(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_mmrc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('is_staff', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('line_user_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['account'])
        batch_op.create_unique_constraint(None, ['line_user_id'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('line_user_id')
        batch_op.drop_column('last_login')
        batch_op.drop_column('phone')
        batch_op.drop_column('gender')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_staff')
        batch_op.drop_column('account')

    op.drop_table('staff_details')
    op.drop_table('questionnaire_mmrc')
    op.drop_table('questionnaire_cat')
    op.drop_table('health_profiles')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
